---
title: Journal
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jimafisk@gmail.com
description: "<h3>Hello, world! Welcome to:</h3><h1>Jim's Dev Journal</h1><h3>A collection
  of my disjointed thoughts about tech.</h3>"
baseurl: ''
url: http://jimafisk.github.io
twitter_username: jimafisk
github_username: jimafisk
markdown: kramdown
